### ISSUE TITLE
Multi-Server Request Reply Sample

### ISSUE THREAD

**Issue by michaelw90** [weixiyen/messenger.js#1]
The below section of the example code has a missing '.

```
setTimeout(function(){
  // request here instead of shout to only access 1 server
  client.request('a message came', {some: 'data}, function(data){
    console.log(data.greetings);
  });
}, 2000);
```

after `some: 'data`, there should be another '.

Just thought I'd help keep the docs accurate.

**Comment by weixiyen** [comment]
Fixed as part of 23b7c7e928b8fa876c50b131da3e413c4ef71c9b
