### ISSUE TITLE
client.request in sample can't run without setInterval

### ISSUE THREAD

**Issue by agad** [weixiyen/messenger.js#4]
Using the code below and just removing the client.requests from the timer loop and issue them individually, results in an error:-1 response code being returned.  Wrap them up in a setInterval again and all is good.

var messenger = require('messenger');

client = messenger.createSpeaker(16000);
server = messenger.createListener(16000);

server.on('give it to me', function(message, data){
    message.reply({'you':'got it'})
});

```
client.request('give it to me', {hello:'world'}, function(data){
    console.log(data);
});
```

client.request('give it to me', {hello:'world'}, function(data){
    console.log(data);
});

client.request('give it to me', {hello:'world'}, function(data){
    console.log(data);
});

**Comment by weixiyen** [comment]
It's working as intended.  The client cannot connect to the server unless the server is bound and client is connected to it.

Without a setInterval, it cannot work simply because the request is made before the connection happens.
